### PR TITLE
Add numeric String with string padded with 0s

### PR DESCRIPTION
**Pull request by nlitwin**

### CODE REVIEW

**Comment by nlitwin** [comment]
@parthshah

**Comment by vikasrohit** [comment]
I have written a filter for pad number a number with 0. npad.filter.js. It should return the padded string.

**Comment by parthshah** [comment]
@vikasrohit - I saw that later, but i think it's best if we handle this in the constants module as well since it's been used by other apps.
Thanks @nlitwin :+1:

**Comment by vikasrohit** [comment]
IMO, we should have our common filters as separate library, if we want to share them between apps. So, the apps should be able to pad or do whatever they want to do with this data. We should not be modifying the data format here, it seems redundant data in the array. :)

**Comment by parthshah** [comment]
Agreed, country "code" can be re-used to handle numeric string.

I do like your idea of a generic filters module. Luckily we do have all the
filters in a separate directory so it should be fairly straightforward to
put the common ones in their own bower module.


On Fri, Nov 6, 2015 at 7:59 AM, vikasrohit <notifications@github.com> wrote:

> IMO, we should have our common filters as separate library, if we want to
> share them between apps. So, the apps should be able to pad or do whatever
> they want to do with this data. We should not be modifying the data format
> here, it seems redundant data in the array. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appirio-tech/ng-iso-constants/pull/5#issuecomment-154447862>
> .
>



-- 
Thanks
Parth Shah

**Pull request merged**
